### ISSUE TITLE
gradle 版本低

### ISSUE THREAD

**Issue by tardistao** [SpikeKing/TestAppBar#1]
Error:Unsupported method: BaseConfig.getApplicationIdSuffix().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model.

**Comment by SpikeKing** [comment]
需要适配gradle版本。

**Comment by tardistao** [comment]
1.project builder.gradle 内容更改：
  classpath 'com.android.tools.build:gradle:2.3.2'
2.gradle-wrapper.properties 内容更改：distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip
3.app builder.gradle 内容更改：buildToolsVersion （看自己的版本）

**Comment by SpikeKing** [comment]
赞👍
